### ISSUE TITLE
error

### ISSUE THREAD

**Issue by GizliBaskan** [holps-7/Instagram-Spam-Bot#9]
https://paste.turingarch.com/paste.php?id=208
how can i fix this?

**Comment by holps-7** [comment]
### Problem
![Screenshot 2022-07-17 at 2 55 21 PM](https://user-images.githubusercontent.com/43104299/179392149-cf91c33b-bcab-4fa1-92a0-12e28a3c4e0f.png)

### Solution
![Screenshot 2022-07-17 at 2 54 56 PM](https://user-images.githubusercontent.com/43104299/179392162-0edf8b48-bb3c-4282-a098-ea5a0f0d200f.png)
You are missing **Quotations marks** in the username part
